### ISSUE TITLE
Theme pages missing H1 tag

### ISSUE THREAD

**Issue by IO-Fire** [hlassiege/bloggr-demo#4]
Some pages in the mistral theme are missing a H1 tag. This tag is used by search engines to understand the page.

**Bing** - *NOTICE : H1 tag missing*:
> The \<h1\> tag is missing. The \<h1\> tag is an indicator to Bingbot and web visitors of what the body copy's primary theme or topic is. The \<h1\> tag reinforces the core keyword(s) found in the title, description and the body copy. We recommend that the \<h1\> tag includes keywords that reflect the contents of the page and that it is not longer than approximately 150 characters in length.
### Examples

- [https://mistral.bloggrify.com](https://mistral.bloggrify.com)
  - [`layouts/themes/mistral/home.vue`](https://github.com/bloggrify/bloggrify-mistral/blob/4dde78b69f8c827d9c5c9d0ee65fa0775c2f3b6a/layouts/themes/mistral/home.vue#L1)

- [https://mistral.bloggrify.com/archives](https://mistral.bloggrify.com/archives)
  - [`layouts/themes/mistral/archive.vue`](https://github.com/bloggrify/bloggrify-mistral/blob/4dde78b69f8c827d9c5c9d0ee65fa0775c2f3b6a/layouts/themes/mistral/archive.vue#L3-L5)

## Potential Fix

- Replace `h2` tag with `h1` on `/archives` page.
- Add `h1` tag to `/` (home) page

**Comment by IO-Fire** [comment]
Suggested title of `h1` tag on `/` (home) page: "**Posts**"

**Comment by hlassiege** [comment]
thanks for the report :)
